#!/bin/sh
# Build both distributions from the one readable source, bookmarklet.src.js.
# Edit bookmarklet.src.js (multi-line, normal quotes), then run: ./build.sh
#
# Outputs:
#   x-print-bookmarklet        select-all + copy this into the bookmark URL field
#   extension/print-article.js the same code as a plain script for the Chrome
#                              extension to inject (generated; do not hand-edit)
#
# Bookmarklet: strip the indentation from each line, join all lines with a
# single space (always a safe token separator in JS), then URL-encode the
# single quotes as %27 so they survive being pasted into a bookmark URL.
# Extension: drop the leading javascript: scheme; the rest is already a valid
# IIFE.
set -e
cd "$(dirname "$0")"
sed 's/^[[:space:]]*//' bookmarklet.src.js | tr '\n' ' ' | sed "s/'/%27/g" | sed 's/ *$//' > x-print-bookmarklet
echo "Built x-print-bookmarklet ($(wc -c < x-print-bookmarklet | tr -d ' ') bytes)"

{
  echo "// GENERATED by build.sh from bookmarklet.src.js - do not edit directly."
  sed '1s|^javascript:||' bookmarklet.src.js
} > extension/print-article.js
echo "Built extension/print-article.js ($(wc -c < extension/print-article.js | tr -d ' ') bytes)"
